services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    
  postgres:
    image: postgres:15
    container_name: hive-metastore-postgres
    environment:
      POSTGRES_DB: metastore
      POSTGRES_USER: hive
      POSTGRES_PASSWORD: hive
      POSTGRES_INITDB_ARGS: "--auth-host=md5 --auth-local=md5"
    ports:
      - "5433:5432"
    volumes:
      - metastore_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hive -d metastore"]
      interval: 5s
      timeout: 5s
      retries: 10

  hive-metastore:
    image: starburstdata/hive-metastore:latest
    container_name: hive-metastore
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
      HIVE_METASTORE_DRIVER: org.postgresql.Driver
      HIVE_METASTORE_USER: hive
      HIVE_METASTORE_PASSWORD: hive
      HIVE_METASTORE_KERBEROS_PRINCIPAL: ""
    ports:
      - "9083:9083"



  trino:
    image: trinodb/trino:latest
    container_name: trino
    depends_on:
      - hive-metastore
    ports:
      - "8080:8080"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./trino/etc:/etc/trino

volumes:
  minio_data:
  metastore_db: