connector.name=hive
hive.metastore.uri=thrift://hive-metastore:9083

# Trino 479: Native S3 filesystem
fs.native-s3.enabled=true

# MinIO
s3.endpoint=http://minio:9000
s3.path-style-access=true
s3.region=us-east-1

# credenciales desde env del contenedor trino
s3.aws-access-key=${ENV:MINIO_ROOT_USER}
s3.aws-secret-key=${ENV:MINIO_ROOT_PASSWORD}

# recomendado
hive.non-managed-table-writes-enabled=true
hive.create-empty-bucket-files=false
